
package com.etz.app3d.bankservices.unity.accountquery.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "APISoap", targetNamespace = "http://unitybankng.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface APISoap {


    /**
     * 
     * @param accountNumber
     * @return
     *     returns com.unitybankng.ArrayOfAccountDetail
     */
    @WebMethod(action = "http://unitybankng.com/fetchAccountDetail")
    @WebResult(name = "fetchAccountDetailResult", targetNamespace = "http://unitybankng.com/")
    @RequestWrapper(localName = "fetchAccountDetail", targetNamespace = "http://unitybankng.com/", className = "com.unitybankng.FetchAccountDetail")
    @ResponseWrapper(localName = "fetchAccountDetailResponse", targetNamespace = "http://unitybankng.com/", className = "com.unitybankng.FetchAccountDetailResponse")
    public ArrayOfAccountDetail fetchAccountDetail(
        @WebParam(name = "accountNumber", targetNamespace = "http://unitybankng.com/")
        String accountNumber);

    /**
     * 
     * @param accountNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "NameEnquiry", action = "http://unitybankng.com/NameEnquiry")
    @WebResult(name = "NameEnquiryResult", targetNamespace = "http://unitybankng.com/")
    @RequestWrapper(localName = "NameEnquiry", targetNamespace = "http://unitybankng.com/", className = "com.unitybankng.NameEnquiry")
    @ResponseWrapper(localName = "NameEnquiryResponse", targetNamespace = "http://unitybankng.com/", className = "com.unitybankng.NameEnquiryResponse")
    public String nameEnquiry(
        @WebParam(name = "accountNumber", targetNamespace = "http://unitybankng.com/")
        String accountNumber);

}
