
package com.etz.app3d.bankservices.heritage.accountquery.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "eTranzAuthMethdSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ETranzAuthMethdSoap {


    /**
     * 
     * @param myMobileNumber
     * @param myAccountNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/eTranzHBCMobileAuthentication")
    @WebResult(name = "eTranzHBCMobileAuthenticationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "eTranzHBCMobileAuthentication", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETranzHBCMobileAuthentication")
    @ResponseWrapper(localName = "eTranzHBCMobileAuthenticationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETranzHBCMobileAuthenticationResponse")
    public String eTranzHBCMobileAuthentication(
        @WebParam(name = "myMobileNumber", targetNamespace = "http://tempuri.org/")
        String myMobileNumber,
        @WebParam(name = "myAccountNumber", targetNamespace = "http://tempuri.org/")
        String myAccountNumber);

    /**
     * 
     * @param myMobileNumber
     * @param myAccountNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/eTranzHBCRemittanceUI")
    @WebResult(name = "eTranzHBCRemittanceUIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "eTranzHBCRemittanceUI", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETranzHBCRemittanceUI")
    @ResponseWrapper(localName = "eTranzHBCRemittanceUIResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETranzHBCRemittanceUIResponse")
    public String eTranzHBCRemittanceUI(
        @WebParam(name = "myMobileNumber", targetNamespace = "http://tempuri.org/")
        String myMobileNumber,
        @WebParam(name = "myAccountNumber", targetNamespace = "http://tempuri.org/")
        String myAccountNumber);

    /**
     * 
     * @param myAccountNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/fetchAccountDetail")
    @WebResult(name = "fetchAccountDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "fetchAccountDetail", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FetchAccountDetail")
    @ResponseWrapper(localName = "fetchAccountDetailResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FetchAccountDetailResponse")
    public String fetchAccountDetail(
        @WebParam(name = "myAccountNumber", targetNamespace = "http://tempuri.org/")
        String myAccountNumber);

    /**
     * 
     * @param myCustomerId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/fetchAccountDetailWithId")
    @WebResult(name = "fetchAccountDetailWithIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "fetchAccountDetailWithId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FetchAccountDetailWithId")
    @ResponseWrapper(localName = "fetchAccountDetailWithIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FetchAccountDetailWithIdResponse")
    public String fetchAccountDetailWithId(
        @WebParam(name = "myCustomerId", targetNamespace = "http://tempuri.org/")
        String myCustomerId);

}
