
package com.etz.app3d.bankservices.heritage.accountquery.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "eTranzAuthMethd", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.0.34.210:8080/eTranzHBCAuth/eTranzAuthMethd.asmx?wsdl")
public class ETranzAuthMethd
    extends Service
{

    private final static URL ETRANZAUTHMETHD_WSDL_LOCATION;
    private final static WebServiceException ETRANZAUTHMETHD_EXCEPTION;
    private final static QName ETRANZAUTHMETHD_QNAME = new QName("http://tempuri.org/", "eTranzAuthMethd");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.34.210:8080/eTranzHBCAuth/eTranzAuthMethd.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ETRANZAUTHMETHD_WSDL_LOCATION = url;
        ETRANZAUTHMETHD_EXCEPTION = e;
    }

    public ETranzAuthMethd() {
        super(__getWsdlLocation(), ETRANZAUTHMETHD_QNAME);
    }

    public ETranzAuthMethd(WebServiceFeature... features) {
        super(__getWsdlLocation(), ETRANZAUTHMETHD_QNAME, features);
    }

    public ETranzAuthMethd(URL wsdlLocation) {
        super(wsdlLocation, ETRANZAUTHMETHD_QNAME);
    }

    public ETranzAuthMethd(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ETRANZAUTHMETHD_QNAME, features);
    }

    public ETranzAuthMethd(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ETranzAuthMethd(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ETranzAuthMethdSoap
     */
    @WebEndpoint(name = "eTranzAuthMethdSoap")
    public ETranzAuthMethdSoap getETranzAuthMethdSoap() {
        return super.getPort(new QName("http://tempuri.org/", "eTranzAuthMethdSoap"), ETranzAuthMethdSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ETranzAuthMethdSoap
     */
    @WebEndpoint(name = "eTranzAuthMethdSoap")
    public ETranzAuthMethdSoap getETranzAuthMethdSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "eTranzAuthMethdSoap"), ETranzAuthMethdSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ETRANZAUTHMETHD_EXCEPTION!= null) {
            throw ETRANZAUTHMETHD_EXCEPTION;
        }
        return ETRANZAUTHMETHD_WSDL_LOCATION;
    }

}
