//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.27 at 12:22:34 PM WAT 
//


package com.etz.app3d.bankservices.skye.accountquery.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.etz.app3d.bankservices.skye.accountquery.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.etz.app3d.bankservices.skye.accountquery.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ETZAcctRequestResponse }
     * 
     */
    public ETZAcctRequestResponse createETZAcctRequestResponse() {
        return new ETZAcctRequestResponse();
    }

    /**
     * Create an instance of {@link ETZCustRequest }
     * 
     */
    public ETZCustRequest createETZCustRequest() {
        return new ETZCustRequest();
    }

    /**
     * Create an instance of {@link ETZSkyeXEmailRequest }
     * 
     */
    public ETZSkyeXEmailRequest createETZSkyeXEmailRequest() {
        return new ETZSkyeXEmailRequest();
    }

    /**
     * Create an instance of {@link ETZCustRequestResponse }
     * 
     */
    public ETZCustRequestResponse createETZCustRequestResponse() {
        return new ETZCustRequestResponse();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link ETZAcctATMRequest }
     * 
     */
    public ETZAcctATMRequest createETZAcctATMRequest() {
        return new ETZAcctATMRequest();
    }

    /**
     * Create an instance of {@link ETZPhoneRequest }
     * 
     */
    public ETZPhoneRequest createETZPhoneRequest() {
        return new ETZPhoneRequest();
    }

    /**
     * Create an instance of {@link ETZAcctRequest }
     * 
     */
    public ETZAcctRequest createETZAcctRequest() {
        return new ETZAcctRequest();
    }

    /**
     * Create an instance of {@link ETZAcctMobRequestResponse }
     * 
     */
    public ETZAcctMobRequestResponse createETZAcctMobRequestResponse() {
        return new ETZAcctMobRequestResponse();
    }

    /**
     * Create an instance of {@link ETZAcctMobRequest }
     * 
     */
    public ETZAcctMobRequest createETZAcctMobRequest() {
        return new ETZAcctMobRequest();
    }

    /**
     * Create an instance of {@link ETZPhoneRequestResponse }
     * 
     */
    public ETZPhoneRequestResponse createETZPhoneRequestResponse() {
        return new ETZPhoneRequestResponse();
    }

    /**
     * Create an instance of {@link ETZAcctATMRequestResponse }
     * 
     */
    public ETZAcctATMRequestResponse createETZAcctATMRequestResponse() {
        return new ETZAcctATMRequestResponse();
    }

    /**
     * Create an instance of {@link ETZSkyeXEmailRequestResponse }
     * 
     */
    public ETZSkyeXEmailRequestResponse createETZSkyeXEmailRequestResponse() {
        return new ETZSkyeXEmailRequestResponse();
    }

}
