package com.etz.app3d.bankservices.skye.accountquery.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SkyeWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SkyeWebServiceSoap {


    /**
     * 
     * @param vAcctNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ETZAcctRequest", action = "http://tempuri.org/ETZAcctRequest")
    @WebResult(name = "ETZAcctRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ETZAcctRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZAcctRequest")
    @ResponseWrapper(localName = "ETZAcctRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZAcctRequestResponse")
    public String etzAcctRequest(
        @WebParam(name = "v_acct_no", targetNamespace = "http://tempuri.org/")
        String vAcctNo);

    /**
     * 
     * @param vAcctNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ETZAcctMobRequest", action = "http://tempuri.org/ETZAcctMobRequest")
    @WebResult(name = "ETZAcctMobRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ETZAcctMobRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZAcctMobRequest")
    @ResponseWrapper(localName = "ETZAcctMobRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZAcctMobRequestResponse")
    public String etzAcctMobRequest(
        @WebParam(name = "v_acct_no", targetNamespace = "http://tempuri.org/")
        String vAcctNo);

    /**
     * 
     * @param vPhoneNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ETZPhoneRequest", action = "http://tempuri.org/ETZPhoneRequest")
    @WebResult(name = "ETZPhoneRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ETZPhoneRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZPhoneRequest")
    @ResponseWrapper(localName = "ETZPhoneRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZPhoneRequestResponse")
    public String etzPhoneRequest(
        @WebParam(name = "v_phone_no", targetNamespace = "http://tempuri.org/")
        String vPhoneNo);

    /**
     * 
     * @param vCustNo
     * @return
     *     returns org.tempuri.ArrayOfString
     */
    @WebMethod(operationName = "ETZCustRequest", action = "http://tempuri.org/ETZCustRequest")
    @WebResult(name = "ETZCustRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ETZCustRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZCustRequest")
    @ResponseWrapper(localName = "ETZCustRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZCustRequestResponse")
    public ArrayOfString etzCustRequest(
        @WebParam(name = "v_cust_no", targetNamespace = "http://tempuri.org/")
        String vCustNo);

    /**
     * 
     * @param vAcctNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ETZAcctATMRequest", action = "http://tempuri.org/ETZAcctATMRequest")
    @WebResult(name = "ETZAcctATMRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ETZAcctATMRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZAcctATMRequest")
    @ResponseWrapper(localName = "ETZAcctATMRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZAcctATMRequestResponse")
    public String etzAcctATMRequest(
        @WebParam(name = "v_acct_no", targetNamespace = "http://tempuri.org/")
        String vAcctNo);

    /**
     * 
     * @param vAcctNo
     * @param vPhoneNo
     * @param vEmail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ETZSkyeXEmailRequest", action = "http://tempuri.org/ETZSkyeXEmailRequest")
    @WebResult(name = "ETZSkyeXEmailRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ETZSkyeXEmailRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZSkyeXEmailRequest")
    @ResponseWrapper(localName = "ETZSkyeXEmailRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ETZSkyeXEmailRequestResponse")
    public String etzSkyeXEmailRequest(
        @WebParam(name = "v_acct_no", targetNamespace = "http://tempuri.org/")
        String vAcctNo,
        @WebParam(name = "v_phone_no", targetNamespace = "http://tempuri.org/")
        String vPhoneNo,
        @WebParam(name = "v_email", targetNamespace = "http://tempuri.org/")
        String vEmail);

}
