package com.etz.app3d.bankservices.skye.accountquery.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SkyeWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.100.32/SkyeWeb/SkyeWebService.asmx?wsdl")
public class SkyeWebService
    extends Service
{

    private final static URL SKYEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SKYEWEBSERVICE_EXCEPTION;
    private final static QName SKYEWEBSERVICE_QNAME = new QName("http://tempuri.org/", "SkyeWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.100.32/SkyeWeb/SkyeWebService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SKYEWEBSERVICE_WSDL_LOCATION = url;
        SKYEWEBSERVICE_EXCEPTION = e;
    }

    public SkyeWebService() {
        super(__getWsdlLocation(), SKYEWEBSERVICE_QNAME);
    }

    public SkyeWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SKYEWEBSERVICE_QNAME, features);
    }

    public SkyeWebService(URL wsdlLocation) {
        super(wsdlLocation, SKYEWEBSERVICE_QNAME);
    }

    public SkyeWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SKYEWEBSERVICE_QNAME, features);
    }

    public SkyeWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SkyeWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SkyeWebServiceSoap
     */
    @WebEndpoint(name = "SkyeWebServiceSoap")
    public SkyeWebServiceSoap getSkyeWebServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "SkyeWebServiceSoap"), SkyeWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SkyeWebServiceSoap
     */
    @WebEndpoint(name = "SkyeWebServiceSoap")
    public SkyeWebServiceSoap getSkyeWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "SkyeWebServiceSoap"), SkyeWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SKYEWEBSERVICE_EXCEPTION!= null) {
            throw SKYEWEBSERVICE_EXCEPTION;
        }
        return SKYEWEBSERVICE_WSDL_LOCATION;
    }

}
