//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.12 at 04:29:39 PM WAT 
//


package com.etz.app3d.bankservices.fcmb.accountquery.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.etz.app3d.services.fcmb.accountquery.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.etz.app3d.services.fcmb.accountquery.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Customeraccountdetail }
     * 
     */
    public Customeraccountdetail createCustomeraccountdetail() {
        return new Customeraccountdetail();
    }

    /**
     * Create an instance of {@link Customerdraftaccountdetail }
     * 
     */
    public Customerdraftaccountdetail createCustomerdraftaccountdetail() {
        return new Customerdraftaccountdetail();
    }

    /**
     * Create an instance of {@link CustomeraccountdetailResponse }
     * 
     */
    public CustomeraccountdetailResponse createCustomeraccountdetailResponse() {
        return new CustomeraccountdetailResponse();
    }

    /**
     * Create an instance of {@link CustomerPhoneValidationResponse }
     * 
     */
    public CustomerPhoneValidationResponse createCustomerPhoneValidationResponse() {
        return new CustomerPhoneValidationResponse();
    }

    /**
     * Create an instance of {@link Customerbycustid }
     * 
     */
    public Customerbycustid createCustomerbycustid() {
        return new Customerbycustid();
    }

    /**
     * Create an instance of {@link Inputencrpt }
     * 
     */
    public Inputencrpt createInputencrpt() {
        return new Inputencrpt();
    }

    /**
     * Create an instance of {@link CustomerinfoResponse }
     * 
     */
    public CustomerinfoResponse createCustomerinfoResponse() {
        return new CustomerinfoResponse();
    }

    /**
     * Create an instance of {@link CustomerdraftaccountdetailResponse }
     * 
     */
    public CustomerdraftaccountdetailResponse createCustomerdraftaccountdetailResponse() {
        return new CustomerdraftaccountdetailResponse();
    }

    /**
     * Create an instance of {@link Accountbalance }
     * 
     */
    public Accountbalance createAccountbalance() {
        return new Accountbalance();
    }

    /**
     * Create an instance of {@link AccountbalanceResponse }
     * 
     */
    public AccountbalanceResponse createAccountbalanceResponse() {
        return new AccountbalanceResponse();
    }

    /**
     * Create an instance of {@link CustomerPhoneValidation }
     * 
     */
    public CustomerPhoneValidation createCustomerPhoneValidation() {
        return new CustomerPhoneValidation();
    }

    /**
     * Create an instance of {@link CustomerbycustidResponse }
     * 
     */
    public CustomerbycustidResponse createCustomerbycustidResponse() {
        return new CustomerbycustidResponse();
    }

    /**
     * Create an instance of {@link Inputdecript }
     * 
     */
    public Inputdecript createInputdecript() {
        return new Inputdecript();
    }

    /**
     * Create an instance of {@link InputdecriptResponse }
     * 
     */
    public InputdecriptResponse createInputdecriptResponse() {
        return new InputdecriptResponse();
    }

    /**
     * Create an instance of {@link InputencrptResponse }
     * 
     */
    public InputencrptResponse createInputencrptResponse() {
        return new InputencrptResponse();
    }

    /**
     * Create an instance of {@link Customerinfo }
     * 
     */
    public Customerinfo createCustomerinfo() {
        return new Customerinfo();
    }

}
