package com.etz.app3d.bankservices.fcmb.accountquery.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param vforcid
     * @param vusername
     * @param vphone
     * @param vpasswd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/customerPhoneValidation")
    @WebResult(name = "customerPhoneValidationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "customerPhoneValidation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CustomerPhoneValidation")
    @ResponseWrapper(localName = "customerPhoneValidationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CustomerPhoneValidationResponse")
    public String customerPhoneValidation(
        @WebParam(name = "vforcid", targetNamespace = "http://tempuri.org/")
        String vforcid,
        @WebParam(name = "vphone", targetNamespace = "http://tempuri.org/")
        String vphone,
        @WebParam(name = "vusername", targetNamespace = "http://tempuri.org/")
        String vusername,
        @WebParam(name = "vpasswd", targetNamespace = "http://tempuri.org/")
        String vpasswd);

    /**
     * 
     * @param vforacid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/customerinfo")
    @WebResult(name = "customerinfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "customerinfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Customerinfo")
    @ResponseWrapper(localName = "customerinfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CustomerinfoResponse")
    public String customerinfo(
        @WebParam(name = "vforacid", targetNamespace = "http://tempuri.org/")
        String vforacid);

    /**
     * 
     * @param vcustid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/customerbycustid")
    @WebResult(name = "customerbycustidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "customerbycustid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Customerbycustid")
    @ResponseWrapper(localName = "customerbycustidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CustomerbycustidResponse")
    public String customerbycustid(
        @WebParam(name = "vcustid", targetNamespace = "http://tempuri.org/")
        String vcustid);

    /**
     * 
     * @param vforacid
     * @param vusername
     * @param vpasswd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/customeraccountdetail")
    @WebResult(name = "customeraccountdetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "customeraccountdetail", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Customeraccountdetail")
    @ResponseWrapper(localName = "customeraccountdetailResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CustomeraccountdetailResponse")
    public String customeraccountdetail(
        @WebParam(name = "vforacid", targetNamespace = "http://tempuri.org/")
        String vforacid,
        @WebParam(name = "vusername", targetNamespace = "http://tempuri.org/")
        String vusername,
        @WebParam(name = "vpasswd", targetNamespace = "http://tempuri.org/")
        String vpasswd);

    /**
     * 
     * @param vforacid
     * @param vusername
     * @param vpasswd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/customerdraftaccountdetail")
    @WebResult(name = "customerdraftaccountdetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "customerdraftaccountdetail", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Customerdraftaccountdetail")
    @ResponseWrapper(localName = "customerdraftaccountdetailResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CustomerdraftaccountdetailResponse")
    public String customerdraftaccountdetail(
        @WebParam(name = "vforacid", targetNamespace = "http://tempuri.org/")
        String vforacid,
        @WebParam(name = "vusername", targetNamespace = "http://tempuri.org/")
        String vusername,
        @WebParam(name = "vpasswd", targetNamespace = "http://tempuri.org/")
        String vpasswd);

    /**
     * 
     * @param straccountno
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Inputdecript", action = "http://tempuri.org/Inputdecript")
    @WebResult(name = "InputdecriptResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Inputdecript", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Inputdecript")
    @ResponseWrapper(localName = "InputdecriptResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InputdecriptResponse")
    public String inputdecript(
        @WebParam(name = "straccountno", targetNamespace = "http://tempuri.org/")
        String straccountno);

    /**
     * 
     * @param straccountno
     * @param passwd
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Inputencrpt", action = "http://tempuri.org/Inputencrpt")
    @WebResult(name = "InputencrptResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Inputencrpt", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Inputencrpt")
    @ResponseWrapper(localName = "InputencrptResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InputencrptResponse")
    public String inputencrpt(
        @WebParam(name = "straccountno", targetNamespace = "http://tempuri.org/")
        String straccountno,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "passwd", targetNamespace = "http://tempuri.org/")
        String passwd);

    /**
     * 
     * @param vforacid
     * @param vusername
     * @param vpasswd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/accountbalance")
    @WebResult(name = "accountbalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "accountbalance", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Accountbalance")
    @ResponseWrapper(localName = "accountbalanceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AccountbalanceResponse")
    public String accountbalance(
        @WebParam(name = "vforacid", targetNamespace = "http://tempuri.org/")
        String vforacid,
        @WebParam(name = "vusername", targetNamespace = "http://tempuri.org/")
        String vusername,
        @WebParam(name = "vpasswd", targetNamespace = "http://tempuri.org/")
        String vpasswd);

}
